Repository jenkinsci/cppcheck-plugin, pull requests merged in 2022-05, with the labels that each got.

#57 Update plugin parent POM
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#59 Enable Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: internal

#58 Add Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: test

#60 Add Dependabot configuration
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: internal

#62 Test on Java 11
  Jenkinsfile
Labels: test

#63 Migrate documentation from wiki
  CHANGELOG.md
  README.md
  docs/images/1.15_config.png
Labels: documentation

#64 [JENKINS-63808] cppcheck is not compatible with Java 11
  src/main/java/com/thalesgroup/hudson/plugins/cppcheck/parser/CppcheckParser.java
  src/main/java/org/jenkinsci/plugins/cppcheck/parser/CppcheckParser.java
Labels: bug

#52 [JENKINS-42613] Cppcheck publisher has no access to source files
  src/main/java/com/thalesgroup/hudson/plugins/cppcheck/CppcheckSource.java
  src/main/java/com/thalesgroup/hudson/plugins/cppcheck/model/CppcheckWorkspaceFile.java
Labels: bug
